pg_gm_db_template_from_file Template_ArchRequestStartDate
pg_gm_db_template_str_replace #Appendix#
pg_gm_db_template_str_replace #Table# ArchDay
pg_gm_db_template_str_replace #IntrvLen# day
pg_gm_db_template_str_replace #Identifier# _ID_Prm
pg_gm_db_template_str_replace #Condition# ID_Prm = _ID_Prm